<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d2ef0984-92bd-496a-889d-abe550655014}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
Elevation : FB_Elevation;
Azimuth : FB_Azimuth;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Elevation();
Azimuth();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="38" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>